Repository duobloom/frontend, pull requests merged in 2024-11, with the labels that each got.

#25 feature/yth/page-feed: 피드 상세 페이지 마크업 및 디자인
  package-lock.json
  package.json
  src/assets/icon/icon-camera.svg
  src/assets/icon/icon-circle-close.svg
  src/assets/icon/icon-edit.svg
  src/assets/icon/icon-plus.svg
  src/assets/icon/icon-smiley-happy.svg
  src/assets/icon/index.ts
  src/components/common/AlertDialog.tsx
  src/components/common/Drawer.tsx
  src/components/common/EmotionBox.tsx
  src/components/common/FeedBox.tsx
  src/components/common/PostBox.tsx
  src/components/common/QuestionBox.tsx
  src/components/common/index.ts
  src/components/feed/CommentInput.tsx
  src/components/feed/FeedComment.tsx
  src/components/feed/FeedHeader.tsx
  src/components/feed/FeedPost.tsx
  src/components/feed/index.ts
  src/components/layout/Header.tsx
  src/components/layout/Nav.tsx
  src/components/main/MainAddButton.tsx
  src/components/main/MainEmotionForm.tsx
  src/components/main/MainFeed.tsx
  src/components/main/MainQuestionForm.tsx
  src/components/main/MainTextForm.tsx
  src/components/main/index.ts
  src/components/ui/LikeAndComments.tsx
  src/pages/FeedDetailPage.tsx
  src/pages/MainPage.tsx
  src/routes/Router.tsx
  src/types/CommentType.ts
  src/types/EmotionType.ts
  src/types/FeedType.ts
  src/types/PostType.ts
  src/types/QuestionType.ts
  src/types/UserType.ts
  tailwind.config.ts
Labels: ♻️ 리팩토링, 🎨 디자인

#27 feature/yth/page-main : 메인 페이지 마크업 및 디자인
  src/components/common/CommentBox.tsx
  src/components/common/CommentInput.tsx
  src/components/common/CommunityBox.tsx
  src/components/common/FeedBox.tsx
  src/components/common/PostDetailBox.tsx
  src/components/common/index.ts
  src/components/feed/FeedHeader.tsx
  src/components/feed/index.ts
  src/components/ui/IconDotHorizontal.tsx
  src/components/ui/LikeAndComments.tsx
  src/pages/PostDetailPage.tsx
  src/routes/Router.tsx
  src/types/BasePostType.ts
  src/types/CommunityType.ts
  src/types/FeedType.ts
  src/types/PostType.ts
  src/types/index.ts
Labels: ♻️ 리팩토링, ⚙️ 개발환경, 🎨 디자인

#31 feature/yth/page-community : 커뮤니티 페이지 마크업 및 디자인
  src/assets/image/doctor1.png
  src/assets/image/doctor2.png
  src/assets/image/test-magazine.jpg
  src/components/common/CommunityBox.tsx
  src/components/common/FilterButton.tsx
  src/components/common/index.ts
  src/components/community/CommunityMagazine.tsx
  src/components/community/CommunityOpenChat.tsx
  src/components/community/CommunityPostList.tsx
  src/components/community/CommunityTitle.tsx
  src/components/community/index.ts
  src/components/ui/Author.tsx
  src/pages/CommunityPage.tsx
  src/routes/Router.tsx
  src/types/CommunityType.ts
  tailwind.config.ts
Labels: ♻️ 리팩토링, 🎨 디자인

#33 feature/pej/page policy : 정책 리스트 페이지, 정책 상세 페이지 디자인
  src/components/common/OptionBoxes.tsx
  src/components/policy/PolicyInfoBox.tsx
  src/constant/PolicyOptions.ts
  src/constant/index.ts
  src/pages/PolicyInfoPage.tsx
  src/pages/PolicyPage.tsx
  src/routes/Router.tsx
Labels: ⚙️ 개발환경, 🎨 디자인

#35 feature/yth/page-community-write : 커뮤니티 페이지 글 작성 마크업 및 디자인
  package-lock.json
  package.json
  src/assets/icon/icon-circle-close.svg
  src/components/common/CommunityBox.tsx
  src/components/common/Drawer.tsx
  src/components/common/FeedBox.tsx
  src/components/common/PostForm.tsx
  src/components/common/form/FormCategoryButton.tsx
  src/components/common/form/FormImage.tsx
  src/components/common/form/FormTag.tsx
  src/components/common/form/index.ts
  src/components/common/index.ts
  src/components/community/CommunityPostList.tsx
  src/components/community/CommunityWriteButton.tsx
  src/components/community/index.ts
  src/components/feed/FeedHeader.tsx
  src/components/main/MainAddButton.tsx
  src/components/main/MainTextForm.tsx
  src/components/main/index.ts
  src/components/ui/Form.tsx
  src/components/ui/Label.tsx
  src/constants/categoryList.ts
  src/hooks/useDraggable.ts
  src/pages/CommunityPage.tsx
  src/types/CommunityType.ts
  src/types/FeedType.ts
  src/types/index.ts
Labels: ♻️ 리팩토링, 🎨 디자인, 🐞 버그

#36 feature/pej/page-hospital : Axios , TanStack Query 라이브러리 설정
  package-lock.json
  package.json
  src/App.tsx
  src/components/common/index.ts
Labels: ⚙️ 개발환경

#38 feature/yth/page-login : 로그인 페이지 마크업 및 디자인, 기능 개발
  src/App.tsx
  src/apis/user/postLogin.ts
  src/components/common/Input.tsx
  src/components/ui/Form.tsx
  src/hooks/useLogin.ts
  src/pages/LoginPage.tsx
  src/routes/Router.tsx
  src/types/LoginType.ts
  src/types/index.ts
  vite.config.ts
Labels: ⚙️ 개발환경, 🎨 디자인, 🛠️ 기능개발

#41 feature/pej/page-hospital : 병원 리스트 페이지 비동기 API요청 데이터 적용 및 디자인 수정
  src/apis/hospital/getFilterHospital.ts
  src/apis/index.ts
  src/components/common/InfoBox.tsx
  src/components/hospital/GetRegionName.tsx
  src/components/hospital/HospitalInfo.tsx
  src/components/hospital/RegionSelecter.tsx
  src/components/hospital/index.ts
  src/components/ui/Box.tsx
  src/constants/Department.ts
  src/constants/Region.ts
  src/pages/HospitalPage.tsx
  src/types/HospitalType.ts
  src/types/PolicyType.ts
  src/types/index.ts
Labels: ♻️ 리팩토링, ⚙️ 개발환경, 🎨 디자인

#42 feature/yth/post-write : 피드 글 작성 기능 구현
  src/apis/image/imageUpload.ts
  src/apis/main/postBoardWrite.ts
  src/components/common/PostForm.tsx
  src/components/common/form/FormCategoryButton.tsx
  src/components/common/form/FormImage.tsx
  src/components/community/CommunityPostList.tsx
  src/constants/CategoryList.ts
  src/hooks/usePostBoardWrite.ts
  src/pages/CommunityPage.tsx
  src/types/BasePostType.ts
  src/types/BoardType.ts
  src/types/CommunityType.ts
  src/types/index.ts
  src/utils/imageResize.ts
  src/utils/index.ts
  vite.config.ts
Labels: ♻️ 리팩토링, 🛠️ 기능개발

#44 refactor/yth/type-edit : 메인 페이지 전체 타입 수정
  src/types/BasePostType.ts
  src/types/CommentType.ts
  src/types/EmotionType.ts
  src/types/QuestionType.ts
Labels: ♻️ 리팩토링

#45 feature/pej/page-hospital : 병원 상세 페이지 & 병원 지도 페이지 API 생성 및 데이터 적용
  src/apis/hospital/getFilterHospital.ts
  src/apis/hospital/getHospitalInfo.ts
  src/apis/index.ts
  src/assets/icon/icon-reddot.png
  src/components/common/InfoBox.tsx
  src/components/common/OptionBoxes.tsx
  src/components/hospital/GetRegionName.tsx
  src/components/hospital/KakaoMap.tsx
  src/components/hospital/RegionSelecter.tsx
  src/pages/HospitalInfoPage.tsx
  src/pages/HospitalMapPage.tsx
  src/pages/HospitalPage.tsx
  src/types/HospitalType.ts
Labels: ♻️ 리팩토링, 🛠️ 기능개발

#43 refactor/yth/design : 반응형 디자인 및 css 수정
  index.html
  package-lock.json
  package.json
  src/App.tsx
  src/components/main/MainDayAndPoint.tsx
  src/components/main/MainFeed.tsx
  src/pages/CalendarDetailPage.tsx
  src/pages/MainPage.tsx
  tailwind.config.ts
Labels: ♻️ 리팩토링, ⚙️ 개발환경, 🎨 디자인

#46 feature/yth/page-main : 메인 페이지 Feed 데이터 조회 기능 구현
  src/apis/main/getFeedDataAPI.ts
  src/apis/main/postBoardWriteAPI.ts
  src/components/board/BoardHeader.tsx
  src/components/common/BoardBox.tsx
  src/components/common/EmotionBox.tsx
  src/components/common/QuestionBox.tsx
  src/components/main/MainFeed.tsx
  src/components/main/index.ts
  src/components/ui/LikeAndComments.tsx
  src/hooks/useErrorHandler.ts
  src/hooks/useGetFeedData.ts
  src/hooks/usePostBoardWrite.ts
  src/pages/PostDetailPage.tsx
  src/types/BasePostType.ts
  src/types/FeedType.ts
  src/types/QuestionType.ts
  src/types/index.ts
  src/utils/formatDateConvert.ts
  src/utils/index.ts
  src/utils/sortFeedData.ts
  src/utils/zodHelpers.ts
Labels: ♻️ 리팩토링, 🛠️ 기능개발

#47 feature/yth/page-calendar : 캘린더 상세 페이지 피드 조회 기능 구현
  src/components/main/MainFeed.tsx
  src/pages/CalendarDetailPage.tsx
  src/types/UserType.ts
Labels: 🛠️ 기능개발

#48 feature/yth/page-main : 유저 포인트 조회 및 캘린더, 검색, 알림 페이지 이동
  src/apis/index.ts
  src/apis/user/getUserTotalPoint.ts
  src/components/main/MainDayAndPoint.tsx
  src/hooks/useGetUserTotalPoint.ts
  src/pages/AlarmPage.tsx
  src/pages/MainPage.tsx
  src/pages/SearchPage.tsx
  src/routes/Router.tsx
Labels: ♻️ 리팩토링, 🛠️ 기능개발

#49 feature/pej/page-hospital : zod 헬퍼 함수 적용으로 유효성 검사 추가 & 병원 키워드 검색 기능 생성
  src/apis/hospital/getFilterHospital.ts
  src/apis/hospital/getHospitalInfo.ts
  src/apis/hospital/getSearchHospital.ts
  src/apis/index.ts
  src/hooks/useGetFilterHospital.ts
  src/hooks/useGetHospitalInfo.ts
  src/hooks/useGetSearchHospital.ts
  src/pages/HospitalInfoPage.tsx
  src/pages/HospitalMapPage.tsx
  src/pages/HospitalPage.tsx
  src/types/HospitalType.ts
Labels: ♻️ 리팩토링, 🛠️ 기능개발

#50 feature/pej/page-mypage : 프로필 수정 요청 기능 생성 & 포인트 거래내역 요청 리팩토링
  src/apis/index.ts
  src/apis/mypage/getMyProfile.ts
  src/apis/mypage/getPointTransaction.ts
  src/apis/mypage/patchMyProfile.ts
  src/components/mypage/NavigateBox.tsx
  src/components/mypage/PointContainer.tsx
  src/components/mypage/TransactionBox.tsx
  src/hooks/useGetPointTransaction.ts
  src/hooks/useUpdateProfile.ts
  src/pages/Mypage/EditMyInfo.tsx
  src/pages/Mypage/MyPage.tsx
  src/pages/Mypage/MyPoint.tsx
  src/pages/Mypage/MyScrap.tsx
  src/types/PointType.ts
  src/types/index.ts
Labels: ♻️ 리팩토링, 🛠️ 기능개발

#51 Feature/yth/page feed
  src/apis/index.ts
  src/apis/posts/deleteComment.ts
  src/apis/posts/deletePostData.ts
  src/apis/posts/getBoardDetailData.ts
  src/apis/posts/getCommunityDetailData.ts
  src/apis/posts/postComment.ts
  src/apis/posts/putBoardUpdate.ts
  src/components/board/BoardHeader.tsx
  src/components/common/BoardBox.tsx
  src/components/common/CommentBox.tsx
  src/components/common/CommentInput.tsx
  src/components/common/Input.tsx
  src/components/common/PostDetailBox.tsx
  src/components/common/PostForm.tsx
  src/components/common/PostHeader.tsx
  src/components/common/index.ts
  src/components/ui/LikeAndComments.tsx
  src/hooks/useDeleteComment.ts
  src/hooks/useDeletePostData.ts
  src/hooks/usePutBoardUpdate.ts
  src/pages/PostDetailPage.tsx
  src/types/BasePostType.ts
  src/types/BoardType.ts
Labels: ♻️ 리팩토링, 🛠️ 기능개발

#55 refactor: 게시글 수정 - 이미지 업로드 부분 코드 변경
  src/apis/image/imageUpload.ts
  src/components/common/PostForm.tsx
  src/hooks/usePutBoardUpdate.ts
Labels: ♻️ 리팩토링

#56 feature/pej/page-search : 검색 페이지 디자인 및 기능 생성
  src/apis/hospital/getSearchHospital.ts
  src/apis/index.ts
  src/apis/policy/getFilterPolicy.ts
  src/apis/policy/getSearchPolicy.ts
  src/components/common/InfoBox.tsx
  src/hooks/useGetFilterPolicy.ts
  src/hooks/useGetSearchHospital.ts
  src/hooks/useGetSearchPolicy.ts
  src/pages/SearchPage.tsx
  src/types/HospitalType.ts
Labels: 🎨 디자인, 🛠️ 기능개발

#57 refactor/yth/page-calendar : 캘린더 페이지 유저 가입 날짜 적용
  src/apis/user/getUserSignupDate.ts
  src/components/common/YearCalendar.tsx
  src/pages/CalendarPage.tsx
Labels: ♻️ 리팩토링, 🛠️ 기능개발

#58 refactor/pej/page-hospital : 병원 지도 컴포넌트 초기값 중복 호출 수정 & 병원 리스트 이미지 타입 변수명 수정
  src/components/hospital/KakaoMap.tsx
  src/pages/HospitalPage.tsx
  src/types/HospitalType.ts
Labels: ♻️ 리팩토링

#59 feature/yth/post-like : 게시글 좋아요 기능 구현
  src/apis/index.ts
  src/apis/posts/postLike.ts
  src/components/common/BoardBox.tsx
  src/components/common/PostDetailBox.tsx
  src/components/ui/LikeAndComments.tsx
  src/hooks/usePostLike.ts
  src/types/BasePostType.ts
Labels: ♻️ 리팩토링, 🛠️ 기능개발

#60 refactor/pej/page-policy : 정책 리스트 페이지에 훅 적용 및 데이터 적용을 위한 수정
  src/pages/PolicyPage.tsx
  src/types/PolicyType.ts
Labels: 🛠️ 기능개발

#61 refactor/yth/comment : 댓글 작성 기능 구현 및 type props 추가로 인한 코드 수정
  src/apis/posts/postComment.ts
  src/components/common/CommentInput.tsx
  src/components/ui/LikeAndComments.tsx
  src/pages/PostDetailPage.tsx
Labels: ♻️ 리팩토링, 🛠️ 기능개발

#62 feature/yth/post-save : 게시글 스크랩 기능 구현
  package-lock.json
  package.json
  src/App.tsx
  src/apis/index.ts
  src/apis/posts/postScrap.ts
  src/components/common/BoardBox.tsx
  src/components/common/PostHeader.tsx
  src/hooks/usePostScrap.ts
Labels: ⚙️ 개발환경, 🛠️ 기능개발

#64 feature/yth/community-get-data : 커뮤니티 인기 글 조회 및 카테고리 별 조회 기능 구현
  src/apis/community/getCommunityPopularList.ts
  src/apis/community/getCommunityTypeList.ts
  src/apis/index.ts
  src/components/common/CommunityBox.tsx
  src/components/community/CommunityPopularList.tsx
  src/components/community/CommunityPostList.tsx
  src/components/community/CommunityTitle.tsx
  src/components/community/index.ts
  src/constants/CategoryList.ts
  src/pages/CommunityPage.tsx
  src/types/CommunityType.ts
  src/utils/formatDateConvert.ts
Labels: ♻️ 리팩토링, 🛠️ 기능개발

#65 feature/yth/community-write : 커뮤니티 글 작성 기능 구현
  src/apis/community/postCommunityWrite.ts
  src/apis/image/imageUpload.ts
  src/apis/index.ts
  src/components/common/PostForm.tsx
  src/components/common/form/FormCategoryButton.tsx
  src/components/common/form/FormImage.tsx
  src/constants/CategoryList.ts
  src/constants/index.ts
  src/hooks/usePostCommunityWrite.ts
  src/types/CommunityType.ts
  src/types/index.ts
Labels: ♻️ 리팩토링, 🛠️ 기능개발

#66 feature/pej/page-scrap : [정책 & 병원] 스크랩 모아보기 페이지 생성 & (get,post,delete) 요청 생성 및 적용
  src/apis/hospital/scrapHospital.ts
  src/apis/index.ts
  src/apis/policy/getPolicyInfo.ts
  src/apis/policy/scrapPolicy.ts
  src/components/common/InfoBox.tsx
  src/components/hospital/DetailBoxes.tsx
  src/components/hospital/KakaoMap.tsx
  src/components/policy/PolicyInfoBox.tsx
  src/hooks/useGetPolicyInfo.ts
  src/hooks/useGetScrapData.ts
  src/pages/HospitalInfoPage.tsx
  src/pages/HospitalPage.tsx
  src/pages/Mypage/MyPage.tsx
  src/pages/Mypage/MyScrap.tsx
  src/pages/PolicyInfoPage.tsx
  src/pages/PolicyPage.tsx
  src/pages/SearchPage.tsx
  src/types/HospitalType.ts
  src/types/PolicyType.ts
Labels: ♻️ 리팩토링, 🎨 디자인, 🛠️ 기능개발

#67 feature/yth/main-profile : 메인 페이지 커플 프로필 조회 기능 구현
  src/components/main/MainProfile.tsx
  src/components/ui/Author.tsx
  src/pages/MainPage.tsx
  src/types/FeedType.ts
  src/types/UserType.ts
Labels: ♻️ 리팩토링, 🛠️ 기능개발

#69 refactor/yth/design : 반응형 디자인 및 css 수정
  src/App.tsx
  src/components/common/AlertDialog.tsx
  src/components/common/Drawer.tsx
  src/components/common/InfoBox.tsx
  src/components/hospital/KakaoMap.tsx
  src/pages/HospitalPage.tsx
  src/pages/PolicyPage.tsx
Labels: ♻️ 리팩토링, 🎨 디자인

#70 Refactor/yth/error handler
  src/App.tsx
  src/apis/axios.ts
  src/apis/errors.ts
  src/apis/main/getFeedDataAPI.ts
  src/apis/main/postBoardWriteAPI.ts
  src/apis/user/getUserTotalPoint.ts
  src/components/main/MainDayAndPoint.tsx
  src/components/main/MainFeed.tsx
  src/components/main/MainProfile.tsx
  src/configs/errorHandler.ts
  src/configs/queryClient.ts
  src/hooks/useErrorHandler.ts
  src/hooks/useGetFeedData.ts
  src/hooks/useGetUserTotalPoint.ts
  src/hooks/usePostBoardWrite.ts
Labels: ♻️ 리팩토링, 🛠️ 기능개발

#71 refactor/pej/error-handler: 에러 핸들러 적용(정책,병원,마이페이지)
  src/apis/hospital/getFilterHospital.ts
  src/apis/hospital/getHospitalInfo.ts
  src/apis/hospital/getSearchHospital.ts
  src/apis/hospital/scrapHospital.ts
  src/apis/index.ts
  src/apis/mypage/getMyProfile.ts
  src/apis/mypage/getPointTransaction.ts
  src/apis/policy/getFilterPolicy.ts
  src/apis/policy/getPolicyInfo.ts
  src/apis/policy/getSearchPolicy.ts
  src/apis/policy/scrapPolicy.ts
  src/hooks/useGetFilterHospital.ts
  src/hooks/useGetFilterPolicy.ts
  src/hooks/useGetHospitalInfo.ts
  src/hooks/useGetMyProfile.ts
  src/hooks/useGetPointTransaction.ts
  src/hooks/useGetPolicyInfo.ts
  src/hooks/useGetScrapData.ts
  src/hooks/useGetSearchHospital.ts
  src/hooks/useGetSearchPolicy.ts
Labels: ♻️ 리팩토링

#72 Refactor/pej/UI design : drawer드래그, 버튼 위치 등 스타일 수정
  src/components/hospital/RegionSelecter.tsx
  src/pages/HospitalInfoPage.tsx
  src/pages/HospitalPage.tsx
  src/pages/Mypage/EditMyInfo.tsx
  src/pages/Mypage/MyScrap.tsx
  src/pages/PolicyInfoPage.tsx
  src/pages/PolicyPage.tsx
  src/pages/SearchPage.tsx
Labels: ♻️ 리팩토링, 🎨 디자인

#74 Refactor/pej/page-data : UI 버그 수정
  src/components/common/OptionBoxes.tsx
  src/components/common/ScrollerableOption.tsx
  src/components/hospital/RegionSelecter.tsx
  src/constants/Department.ts
  src/pages/HospitalInfoPage.tsx
  src/pages/HospitalPage.tsx
  src/pages/PolicyInfoPage.tsx
  src/pages/PolicyPage.tsx
Labels: ♻️ 리팩토링, 🎨 디자인

#76 feature/yth/toast : Toast UI 생성
  package-lock.json
  package.json
  src/App.tsx
  src/libs/custom-toast.tsx
  tailwind.config.ts
Labels: ⚙️ 개발환경, 🛠️ 기능개발

#77 Refactor/pej/page-data : 정책 & 병원 상세 페이지 데이터 적용
  src/assets/image/defaulthospital.png
  src/components/common/InfoBox.tsx
  src/components/hospital/MedicInfo.tsx
  src/constants/MockData.ts
  src/pages/HospitalInfoPage.tsx
  src/pages/PolicyInfoPage.tsx
  src/utils/parseString.ts
Labels: 🎨 디자인, 🛠️ 기능개발

#78 refactor/yth/page-main : ToastUI 추가
  src/components/common/BoardBox.tsx
  src/components/main/MainEmotionForm.tsx
  src/components/main/MainFeed.tsx
  src/components/main/MainQuestionForm.tsx
  src/hooks/useDeletePostData.ts
  src/hooks/useGetFeedData.ts
  src/hooks/usePostBoardWrite.ts
  src/hooks/usePutBoardUpdate.ts
  src/pages/BoardDetailPage.tsx
  src/pages/CalendarDetailPage.tsx
Labels: ♻️ 리팩토링

#79 refactor/yth/page-community : 커뮤니티 페이지 오류 및 query 수정
  src/components/community/CommunityPopularList.tsx
  src/components/community/CommunityPostList.tsx
  src/components/community/CommunityWriteButton.tsx
  src/pages/CommunityDetailPage.tsx
Labels: ♻️ 리팩토링

#80 feature/yth/seo : meta 태그 및 sitemap 추가
  index.html
  public/robots.txt
  public/sitemap.xml
Labels: ♻️ 리팩토링, 🛠️ 기능개발

#81 feature/pej/toast : 내 정보 수정에 toast 적용
  src/components/mypage/EditInput.tsx
  src/pages/Mypage/EditMyInfo.tsx
Labels: 🎨 디자인

#82 Refactor/pej/page-info : 정책 상세 페이지 변경된 데이터 구조에 맞게 스키마 및 기능 구현 수정
  src/pages/HospitalInfoPage.tsx
  src/pages/PolicyInfoPage.tsx
  src/types/PolicyType.ts
Labels: ♻️ 리팩토링, 🎨 디자인, 🛠️ 기능개발

#83 Feature/pej/sticky : 레이지 로딩 & 병원 & 정책 페이지 상단 Sticky 설정
  src/App.tsx
  src/components/common/InfoBox.tsx
  src/components/common/OptionBoxes.tsx
  src/components/common/ScrollerableOption.tsx
  src/pages/HospitalInfoPage.tsx
  src/pages/HospitalPage.tsx
  src/pages/PolicyPage.tsx
  src/utils/imageLazyLoading.tsx
Labels: 🎨 디자인, 🛠️ 기능개발

#85 refactor/yth/develop : develop 브랜치 리팩토링
  src/components/common/Badge.tsx
  src/components/common/InfoBox.tsx
  src/components/common/QuestionBox.tsx
  src/components/main/MainAddButton.tsx
  src/components/main/MainCalendar.tsx
  src/components/main/MainDayAndPoint.tsx
  src/components/main/MainFeed.tsx
  src/components/main/MainProfile.tsx
  src/components/main/MainQuestionForm.tsx
  src/components/mypage/NavigateBox.tsx
  src/components/skeleton/common/AuthorSkeleton.tsx
  src/components/skeleton/common/ButtonSkeleton.tsx
  src/components/skeleton/common/CommentBoxSkeleton.tsx
  src/components/skeleton/common/LikeAndCommentSkeleton.tsx
  src/components/skeleton/common/PostBoxSkeleton.tsx
  src/components/skeleton/detail/DetailPageSkeleton.tsx
  src/components/skeleton/main/QuestionBoxSkeleton.tsx
  src/components/ui/Box.tsx
  src/hooks/useGetUserTotalPoint.ts
  src/pages/BoardDetailPage.tsx
  src/pages/MainPage.tsx
  src/pages/PolicyInfoPage.tsx
  src/utils/imageLazyLoading.tsx
  tailwind.config.ts
Labels: ♻️ 리팩토링, 🎨 디자인, 🛠️ 기능개발

#86 Refactor/pej/design : 병원 & 정책 스켈레톤 UI 적용
  src/App.tsx
  src/assets/icon/icon-userlocation.png
  src/components/common/InfoBox.tsx
  src/components/hospital/KakaoMap.tsx
  src/components/skeleton/DetailInfoSkeleton.tsx
  src/components/skeleton/InfoBoxSkeleton.tsx
  src/pages/HospitalInfoPage.tsx
  src/pages/HospitalMapPage.tsx
  src/pages/HospitalPage.tsx
  src/pages/Mypage/MyPoint.tsx
  src/pages/Mypage/MyScrap.tsx
  src/pages/PolicyInfoPage.tsx
  src/pages/PolicyPage.tsx
  src/pages/SearchPage.tsx
Labels: 🎨 디자인
