Repository duobloom/frontend, pull requests merged in 2024-10, with the labels that each got.

#3 feature/yth/common-button: 공통 컴포넌트 버튼 마크업 및 디자인
  src/components/common/Button.tsx
  src/components/common/index.ts
Labels: 🎨 디자인

#4 Feature/yth/common-info-card: 공통 컴포넌트 뱃지, 박스 마크업 및 디자인
  package-lock.json
  package.json
  src/assets/icon/bookmark.svg
  src/assets/image/test.png
  src/components/common/Badge.tsx
  src/components/common/Box.tsx
  src/components/common/Button.tsx
  src/components/common/index.ts
  src/index.css
  src/types/HospitalType.ts
  src/types/PolicyType.ts
  src/types/index.ts
  src/utils/dDayCalculation.ts
  src/utils/index.ts
  src/vite-env.d.ts
  svg.d.ts
  tailwind.config.ts
  tsconfig.node.json
  vite.config.ts
Labels: ⚙️ 개발환경, 🎨 디자인

#5 Feature/pej/common-input : 공통 컴포넌트 인풋 디자인
  src/components/common/Input.tsx
  src/components/common/index.ts
Labels: 🎨 디자인

#10 feature/pej/common-emotion-box: Emotion 박스 마크업 및 디자인
  src/components/common/EmotionBox.tsx
  src/components/common/index.ts
  src/types/EmotionType.ts
  src/types/index.ts
Labels: 🎨 디자인

#8 feature/yth/common-alarm-box : 공통 컴포넌트 알림 마크업 및 디자인
  src/assets/icon/chevron-right.svg
  src/components/common/AlarmBox.tsx
  src/components/common/InfoBox.tsx
  src/components/common/index.ts
  src/index.css
  tailwind.config.ts
Labels: 🎨 디자인

#9 feature/yth/common-text-box: Feed, Post 박스 마크업 및 디자인
  package-lock.json
  package.json
  src/App.tsx
  src/assets/icon/icon-comments.svg
  src/assets/icon/icon-dot-horizontal.svg
  src/assets/icon/icon-heart.svg
  src/assets/icon/index.ts
  src/components/common/AlarmBox.tsx
  src/components/common/FeedBox.tsx
  src/components/common/InfoBox.tsx
  src/components/common/PostBox.tsx
  src/components/ui/Author.tsx
  src/components/ui/Avatar.tsx
  src/components/ui/Box.tsx
  src/components/ui/Carousel.tsx
  src/components/ui/LikeAndComments.tsx
  src/types/FeedType.ts
  src/types/PostType.ts
  src/types/index.ts
Labels: ♻️ 리팩토링, ⚙️ 개발환경, 🎨 디자인

#13 feature/yth/layout-header: 레이아웃 Header 컴포넌트 마크업 및 디자인
  src/assets/icon/icon-arrow-left.svg
  src/assets/icon/icon-bell.svg
  src/assets/icon/icon-bookmark.svg
  src/assets/icon/icon-chevron-right.svg
  src/assets/icon/icon-search.svg
  src/assets/icon/icon-share.svg
  src/assets/icon/index.ts
  src/components/layout/Header.tsx
Labels: 🎨 디자인, 🙋🏻 질문

#14 feature/pej/common-question-box : Question Box 컴포넌트를 UI 컴포넌트 사용해서 리팩토링
  src/components/common/QuestionBox.tsx
Labels: ♻️ 리팩토링

#15 feature/pej/common-emotion-box : Emotion Box컴포넌트를 UI 컴포넌트 사용해서 리팩토링
  src/components/common/EmotionBox.tsx
Labels: ♻️ 리팩토링

#16 feature/pej/layout-nav : 레이아웃 Navbar 컴포넌트 마크업 및 디자인
  src/assets/icon/icon-nav-community.svg
  src/assets/icon/icon-nav-home.svg
  src/assets/icon/icon-nav-hospital.svg
  src/assets/icon/icon-nav-mypage.svg
  src/assets/icon/icon-nav-policy.svg
  src/assets/icon/index.ts
  src/components/layout/Nav.tsx
Labels: 🎨 디자인
